name = "DataGraphConvert"
uuid = "c6766c74-eb8d-47fa-b824-de2707622bd5"
authors = ["James Kai"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
